### ISSUE TITLE
The method Plugin<h, l>::ensureInitialized does not take the _wasInitialized flag into account

### ISSUE THREAD

**Issue by michaelgregorius** [free-audio/clap-helpers#12]
The method [Plugin<h, l>::ensureInitialized](https://github.com/free-audio/clap-helpers/commit/f8b09cc7154b51999e647dcc3456068a21b9f78a#diff-a3e1bdc2459045d2958bdca0e09e8e6e3e0c4ff4bb7bc9fb92ba4d51f6c834f7R164) does not check the `_wasInitialized` flag. As a result if you have selected something other than `CheckingLevel::None` it will always complain or terminate the plugin.

I assume the code was originally intended to be something like this:
```
if (self._wasInitialized || l == CheckingLevel::None)
     return;
```

**Comment by abique** [comment]
Oh shit you're right!
I fix it immediately.

**Comment by abique** [comment]
I've properly tested the fix this time, all good now.

**Comment by michaelgregorius** [comment]
Thanks for the quick fix and the whole CLAP ecosystem in general!

Just an minor nitpick: I would have evaluated `_wasInitialized` first so that there's the quickest possible exit in the positive case where it is set. I assume that this case should hold most of the times anyway with well-behaved hosts.

**Comment by abique** [comment]
The checking level is a compile constant, so virtually it is checked first already isn't it?

**Comment by michaelgregorius** [comment]
Ah, you're right! I played around with a small example in [Compiler Explorer](https://godbolt.org/) and when optimization is turned on then such a method performs no checks and returns immediately.

Here's the example that I have used in case you are curious and want to paste in the Explorer:
```
#include <iostream>

template<bool b>
class TestClass
{
public:
    TestClass(bool _ano) : ano(_ano) {}

int checkBool()
{
    if (b || ano) return 10;

    return 1;
}

void doBool() const
{
    if (b || ano) return;

    std::cout << "Side effect!";
}

private:
    bool ano;
};

int main(int argc, char*argv)
{
    TestClass<false> t(false);
    t.doBool();
    return t.checkBool();
}
```
If you play around with the template value in the `main` function you will find that the generated code of `doBool` changes. You just have to scroll past the `iostream` noise. I have just included it to have some side effect so that the compiler does not optimize everything away in all cases.
