### ISSUE TITLE
CMake error, INTERFACE_LIBRARY targets may only have whitelisted properties

### ISSUE THREAD

**Issue by madah81pnz1** [free-audio/clap-helpers#13]
```
$ mkdir build
$ cd build
$ cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "POSITION_INDEPENDENT_CODE" is not allowed.


CMake Error at CMakeLists.txt:8 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "CXX_STANDARD" is not allowed.
```
```
$ cmake --version
cmake version 3.18.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Adding prefix INTERFACE_ makes the error go away, but I'm no CMake expert so I'm not sure if this is the right way to do it:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index dd4d991..bf92123 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,8 +6,8 @@ find_package(Catch2 QUIET)
 
 add_library(clap-helpers INTERFACE)
 set_target_properties(clap-helpers PROPERTIES
-    POSITION_INDEPENDENT_CODE ON
-    CXX_STANDARD 11)
+    INTERFACE_POSITION_INDEPENDENT_CODE ON
+    INTERFACE_CXX_STANDARD 11)
 target_include_directories(clap-helpers INTERFACE include)
 target_link_libraries(clap-helpers INTERFACE clap-core)
```

**Comment by madah81pnz1** [comment]
In case someone else has this same problem, the easiest solution is to upgrade to CMake >= 3.19.

The changes introduced in CMake 3.19 allows interface libraries to contain source files:
https://cmake.org/cmake/help/latest/release/3.19.html#other
https://cmake.org/cmake/help/v3.19/manual/cmake-buildsystem.7.html#interface-libraries
> Since CMake 3.19, an INTERFACE library target may optionally contain source files.

Either the minimum version should be increased from 3.17 to 3.19:
`cmake_minimum_required(VERSION 3.19)
`
Or use `INTERFACE_POSITION_INDEPENDENT_CODE` as I suggested in the first post. There seems to be no `INTERFACE_CXX_STANDARD`, so that one has to be removed.

**Comment by abique** [comment]
Hi, `INTERFACE_CXX_STANDARD` doesn't exists.

**Comment by abique** [comment]
I don't think we need to force PIC either, the developer can set it himself on its plugin/host target, and the host may not even need the PIC option.

**Comment by abique** [comment]
@madah81pnz1 thank you very much for the bug report. Please could you confirm the fix? If it doesn't fix the issue for you please can you re-open with logs?
Cheers,
Alex.
