### ISSUE TITLE
ensureMainThread() called for function that is marked thread-safe

### ISSUE THREAD

**Issue by SamWindell** [free-audio/clap-helpers#16]
It's not a common use case, but the clap library says the get_extension function is [thread-safe], but the helper is asserting that it should be from the main thread. Unless I'm misunderstanding something.

https://github.com/free-audio/clap/blob/065d685d4e9657f0344f350eef748be2b4d8e318/include/clap/plugin.h#L98

https://github.com/free-audio/clap-helpers/blob/b458d2f8e3d93249fac80375e937140f99802443/include/clap/helpers/plugin.hxx#L424

**Comment by abique** [comment]
yeah it is a mistake, good catch.
