### ISSUE TITLE
The clap_plugin instance in plugin.hxx contains null pointers until init is called

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/clap-helpers#6]
The spec doesn't allow any of these pointers to be null, so this is a bug:
https://github.com/free-audio/clap-helpers/blob/716cdf49cc6eb7999bad44c084b363bbde907937/include/clap/helpers/plugin.hxx#L116-L130

The plugin should instead just return from these functions (and maybe print something to STDERR) if they are called before init is called.

**Comment by abique** [comment]
The spec also do not allow to call any of those pointers until init is called.

**Comment by robbert-vdh** [comment]
Regardless, they are still not allowed to be null pointers. Or the CLAP spec must specify that all function pointers can be null and that any function pointer must be checked for null values being called to avoid UB. If the plugin needs to enforce that `init()` is called before these functions are called, then the plugin can either just return falsy values from the functions until the plugin is initialized, or in the most extreme case it can raise an assertion failure. This current approach also causes the `clap_plugin` struct pointers to change during the lifetime of the plugin, which I can imagine will also result in some host confusion at some point as they may store some of the function pointers at plugin creation time for whatever reason that might be.

**Comment by abique** [comment]
With null pointers until `init()`, problems will be caught early.
I don't see the benefit in changing that, also `init()` is initializing the object.

**Comment by robbert-vdh** [comment]
Problems will not be caught early. Dereferencing null pointers is undefined behavior, and the host may or may not segfault. In the worst case, everything will appear to work fine until it doesn't anymore. If the goal of this behavior is to make these problems obvious, then the plugin wrapper should just print a message about this and then `std::abort()`. That way there is no danger of invoking undefined behavior, the implementation conforms to the CLAP API (which in its current version has removed all mentions of function pointers being optional), and it's much more obvious what's going on.
